apply plugin: 'com.android.application'

android {
    compileSdkVersion project.properties.compileSdkVersion
    buildToolsVersion project.properties.buildToolsVersion

    defaultConfig {
        applicationId "com.liskovsoft.smarttubesync.controller"
        minSdkVersion 21
        targetSdkVersion project.properties.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            // sin firma especial, apk de debug estandar
        }
    }
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
}
